# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sentiment_analysis_pb2 as sentiment__analysis__pb2


class SentimentAnalysisStub(object):
    """PredictionService provides access to machine-learned models loaded by
    model_servers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/sentiment.analysis.SentimentAnalysis/Predict',
                request_serializer=sentiment__analysis__pb2.PredictRequest.SerializeToString,
                response_deserializer=sentiment__analysis__pb2.PredictResponse.FromString,
                )
        self.SayHello = channel.unary_unary(
                '/sentiment.analysis.SentimentAnalysis/SayHello',
                request_serializer=sentiment__analysis__pb2.HelloRequest.SerializeToString,
                response_deserializer=sentiment__analysis__pb2.HelloReply.FromString,
                )


class SentimentAnalysisServicer(object):
    """PredictionService provides access to machine-learned models loaded by
    model_servers.
    """

    def Predict(self, request, context):
        """Predict -- provides access to loaded TensorFlow model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentimentAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=sentiment__analysis__pb2.PredictRequest.FromString,
                    response_serializer=sentiment__analysis__pb2.PredictResponse.SerializeToString,
            ),
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=sentiment__analysis__pb2.HelloRequest.FromString,
                    response_serializer=sentiment__analysis__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentiment.analysis.SentimentAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SentimentAnalysis(object):
    """PredictionService provides access to machine-learned models loaded by
    model_servers.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sentiment.analysis.SentimentAnalysis/Predict',
            sentiment__analysis__pb2.PredictRequest.SerializeToString,
            sentiment__analysis__pb2.PredictResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sentiment.analysis.SentimentAnalysis/SayHello',
            sentiment__analysis__pb2.HelloRequest.SerializeToString,
            sentiment__analysis__pb2.HelloReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
