using System;
using System.Diagnostics;
using System.IO;


namespace ExecutePythonScript
{
    class Program
    {
        static void Main(string[] args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            //python interprater location
            start.FileName = "python3";
            //argument with file name and input parameters
            start.Arguments = string.Format("{0} {1} {2}", Path.Combine(Directory.GetCurrentDirectory(), "calculator.py"), 5, 10);
            //start.Arguments = string.Format("{0} {1} {2}", Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "../../../calculator.py"), 5, 10);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            //start.LoadUserProfile = true;
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    Console.WriteLine("From System Diagnostics");
                    Console.WriteLine("5 + 10 = {0}", result);
                }
            }

            //Console.ReadLine();
        }
    }
}
